export const IMAGES = {
  STRENGTH: '/img/STRENGTH.png',
  SPEED: '/img/SPEED.png',
  INTELLIGENCE: '/img/INTELLIGENCE.png',
  BEAUTY: '/img/BEAUTY.png',
  TIGER: '/img/TIGER.png',
  SNAIL: '/img/SNAIL.png',
  CHIMP: '/img/CHIMP.png',
  GOLDFISH: '/img/GOLDFISH.png',
  SLOTH: '/img/SLOTH.png',
  CHEETAH: '/img/CHEETAH.png',
  PROBOSCIS_MONKEY: '/img/PROBOSCIS_MONKEY.png',
  WOLF: '/img/WOLF.png',
  SPINNER: '/img/spinner.svg',
};
