export const ATOM_KEY = {
  POSITIVE1: 'POSITIVE1',
  POSITIVE2: 'POSITIVE2',
  NEAGTIVE: 'NEGATIVE',
  PBT: 'PROBABILITY',
  TOAST: 'TOAST',
  LOCALE: 'LOCALE',
};

export const STORAGE_KEY = {
  LOCALE: 'LOCALSTORAGE_LOCALE',
};
